# Generated by Django 5.2.5 on 2025-09-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='gener',
        ),
    ]
