# Generated by Django 5.2.5 on 2025-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_rename_genre_book_gener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='gener',
            field=models.CharField(choices=[('fic', 'Fiction'), ('nfic', 'Non-fiction'), ('sci', 'Sci-Fi'), ('fan', 'Fantasy'), ('bio', 'Biography'), ('oth', 'Other')], default='oth', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
